#! python3

# Usage
# mul <arg1> <arg2> ... <argN> 

import sys
from math import prod
from colored import fg


color = fg(214)

try:
    ans = prod([eval(x) for x in sys.argv[1:]])
    print(color + str(ans).rjust(30))

except:
    print(' usage: mul <number1> <number2> ...')
