#!python3

# Usage
# pow <arg1> <arg2>   
from colored import fg
from sys import argv

color = fg(214)

if len(argv) != 3:
    print('usage: pow <number1> <number2>')
    exit()

try:
    x = eval(argv[1])
    y = eval(argv[2])
    ans = str(pow(x, y))
    print(color + ans.rjust(30))

except:
    print('usage: pow <number1> <number2>')
