#!python3

# Usage
# pow <arg1> <arg2>   
import sys
from colored import fg

color = fg(214)

if len(sys.argv) != 3:
    print('usage: pow <number1> <number2>')
    exit()

try:
    x = eval(sys.argv[1])
    y = eval(sys.argv[2])
    ans = str(pow(x, y))
    print(color + ans.rjust(30))

except:
    print('usage: pow <number1> <number2>')
