#!python3
import sys
from math import sqrt
from colored import fg

green_yellow = fg(154)


def get_arg():
    try:
        return float(sys.argv[1])
    except:
        print('usage: sqrt <number>')
        exit()



print('\n\t' + green_yellow, sqrt(get_arg()), '\n')
