#!/bin/zsh

# Description
# prove terminal supports 24-bit color 
# if it does, output will be a smooth gradient of color

clear;

awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; 
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r, g, b;
        printf "\033[38;2;%d;%d;%dm", 255-r, 255-g, 255-b;
        printf "%s\033[0m", substr(s,colnum%4+1,1);
    }
    printf "\n";
}'

exit 0
