#!python3

import sys
from math import prod
from colored import fg

color = fg(214)

try:
    ans = sum([float(x) for x in sys.argv[1:]])
    print(color + str(ans).rjust(30))

except:
    print('usage: add <number1> <number2> ...')
