#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$h
    amplify add auth        $x # supports social sign-in                            $h
    amplify add api         $x # leverage AppSync, DynamoDB                         $h
    amplify add hosting     $x # deploy f/e to CloudFront, b/e to Amplify           $h
"

exit 0
