#!/bin/zsh

echo "$grey
   commands
   ---------------------------------------------------------------------  $red
    ~ aws iam list-users
    ~ aws s3 ls s3://lorawan-to-snowflake --summarize --human-readable
    ~ aws s3 cp s3://lorawan-to-snowflake/<filename> test.csv
" 

exit 0
