#!/bin/zsh

# Author: James Batman
# Date Created: 12/31/2021
# Last Modified: 12/31/2021

# Description
# convert an integer to a bitset
#  depends on bits2 in /usr/local/bin

# Usage
# bits <int> 

#c='\033[0;32m'
c="$(tput setaf 195)"

if [ $# -eq 0 ]; then
    echo "$c takes a number for an arg"
    exit 0
fi

echo $c
echo "\t $(bits2 $1)"
echo

exit 0
