#!python3
import os
import sys
import subprocess as sp


path  = os.path.expanduser('~/code/ventacity/sbg-webapp/modules/vue-ui/src')
#c     = '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code'
ui    = os.getenv('UI')  # files to open

os.chdir(path)
sp.run('code' + ' ' + ui, shell=True)
