#!/bin/zsh

# Author: James Batman
# Date Created: 12/04/2021
# Last Modified: 12/05/2021

# Description
# print c++ data types and their sizes for current device
#  -- depends on cdata2, a c++ binary

# Usage
# cdata 

cdata2

exit 0
