#!/bin/zsh

# Author: James Batman
# Date Created: 11/12/21
# Last Modified: 11/13/21

# Description
# Prints ANSI colors with codes to the terminal

# Usage
# colors

for i in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
done



## example usage:
#purple='\033[0;35m'
#red='\033[0;31m'
#lightgreen='\033[1;32m'
#lightcyan='\033[0;36m'
#
#echo -e " 
#    ${lightcyan}I ${red}love ${lightgreen}you.
#"

exit 0
