#!/bin/zsh

# Author: James Batman
# Date Created: 11/15/2021
# Last Modified: 11/15/2021

# Description
# copies a folder from volume Andromeda to .

# Usage
# cpfa [dirname | filename]

path=/Volumes/Andromeda/$1
if [ -d $path ]; then
    /bin/cp -r $path .
else
    /bin/cp $path .
fi
 

exit 0
