#!/bin/zsh

# Author: James Batman
# Date Created: 11/15/2021
# Last Modified: 11/15/2021

# Description
# copies a folder from volume Andromeda to .

# Usage
# cpfa [dirname]

dir=$1
cp -r "/Volumes/Andromeda/$dir" .

exit 0
