#!/bin/zsh

# Author: James Batman
# Date Created: 11/20/2021
# Last Modified: 11/20/2021

# Description
# Generate .h file for C++ projects 

# Usage
# c-h <classname> 

classname=$1

lines="#ifndef ${(U)classname}_H
#define ${(U)classname}_H

using namespace std;

class ${(C)classname} {
    public: 
        ${(C)classname}() {}
    private:
};

#endif"

echo $lines > $classname.h


exit 0
