#!/bin/zsh

# Author: James Batman
# Date Created: 11/15/2021
# Last Modified: 11/15/2021

# Description
# copy directory or file to volume Andromeda

# Usage
# cpta [dirname | filename]

path=/Volumes/Andromeda

if [ -d $path ]; then
    /bin/cp -r $1 $path
else
    /bin/cp $1 $path
fi

exit 0
