#!/bin/zsh

# Description
# start a 3-node cluster 

# Usage
# cr_cluster 

c="$(tput setaf 220)"
c2="$(tput setaf 250)"

echo "$c2 starting node1 $c"
cockroach start --insecure --store=node1 \
                --listen-addr=localhost:26257 \
                --http-addr=localhost:8080 \
                --join=localhost:26257,localhost:26258,localhost:26259 \
                --background;

echo "$c2 starting node2 $c"
cockroach start --insecure --store=node2 \
                --listen-addr=localhost:26258 \
                --http-addr=localhost:8081 \
                --join=localhost:26257,localhost:26258,localhost:26259 \
                --background;

echo "$c2 starting node3 $c"
cockroach start --insecure --store=node3 \
                --listen-addr=localhost:26259 \
                --http-addr=localhost:8082 \
                --join=localhost:26257,localhost:26258,localhost:26259 \
                --background;

echo "$c2 initializing cluster $c"
cockroach init --insecure --host=localhost:26257;
#cockroach workload init movr;

exit 0
