#!python3

'''
    Usage: ~ crdb "<CRDB query to execute>"
'''
import os
import sys
import argparse
import subprocess as sp


cnx_str = os.getenv('UBX_GLOBAL')
filename = 'output.csv'


def cmd():
    query = parse_arguments()
    return ['cockroach', 'sql', '--url', cnx_str, '-e', query]


def parse_arguments():
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('query', type=str, nargs='+')
    args = parser.parse_args()
    return ' '.join(args.query)


def bat_file():
    print()
    sp.run(['bat', filename])
    print()


def main():
    with open(filename, 'w') as f:
        try:
            sp.run(cmd(), stdout=f, stderr=sp.PIPE, check=True)
        except sp.CalledProcessError as e:
            print(f"command \n\n { parse_arguments() } \n\n returned non-zero exit status {e.returncode}.", file=sys.stderr)
            print(e.stderr.decode(), file=sys.stderr)


main()
bat_file()
