#!/bin/zsh

# Author: James Batman
# Date Created: 11/17/2021
# Last Modified: 11/17/2021

# Description
# Creates starter zsh script 

# Usage
# createscript <name_of_script> 

name=$1

echo "#!/bin/zsh

# Author: James Batman
# Date Created: 
# Last Modified: 

# Description
# 

# Usage
# 

r=\$red; g=\$gold; y=\$yellow; a=\$aqua; pg=\$palegreen; k=\$khaki;
c=\$cyan; x=\$grey; s=\$sea; gr=\$green; p=\$pink; h=\$honeydew; rs=\$rose;
z=\"\$(tput setaf 63)\"
clear;

echo \"\$h
\"

exit 0" >> $name

/bin/chmod 744 $name
~/nvim-osx64/bin/nvim $name

exit 0
