#! python
'''
    copy csv to tsv
'''
import csv
from csv import reader, writer
from sys import argv
from pathlib import Path


inpath = Path(argv[1])
outpath = inpath.with_suffix('.tsv')


def convert_csv_to_tsv():
    with open(inpath, encoding='utf-8') as csv_file:
        csv_reader = reader(csv_file)
        with open(outpath, mode='w', encoding='utf-8') as tsv_file:
            tsv_writer = writer(tsv_file, delimiter='\t')
            for row in csv_reader:
                tsv_writer.writerow(row)


convert_csv_to_tsv()
print(f'converted {inpath} → {outpath}')
