#!python3

import os
import sys
from cryptography.fernet import Fernet
from colored import fg

c1 = fg(189)
c2 = fg(202)

if len(sys.argv) != 3:
    print("usage: enc <name_of_file_to_decrypt> <name_of_decrypted_file>")
    exit()

file1 = sys.argv[1]   # file to decrypt
file2 = sys.argv[2]   # decrypted file

keypath = os.path.expanduser('~/code/key.key')

def load_key():
    f = open(keypath, 'rb')
    key = f.read()
    f.close()
    return key

with open(file1, 'rb') as f:
    print(f'\t {c2} reading {c1 + file1}..')
    encrypted_data = f.read()

key = load_key()
fr = Fernet(key)         # initialize Fernet

decrypted_data = fr.decrypt(encrypted_data)
with open(file2, 'wb') as f:
    f.write(decrypted_data)

print(f'\t {c2} decrypted {c1 + file1} {c2}as {c1 + file2}')
