#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

echo "
   $x locations $h
    /opt/homebrew/opt/isc-dhcp
    /opt/homebrew/etc/dhcpd.conf
    /opt/homebrew/etc/dhcpd6.conf

    ~ brew services restart isc-dhcp
    ~ brew services stop isc-dhcp
"

exit 0
