#! python3

# Usage
# div <arg1> <arg2>

import sys
from colored import fg


color = fg(214)

try:
    ans = float(eval(sys.argv[1])) / float(eval(sys.argv[2]))
    print(color + str(ans).rjust(30))

except:
    print('usage: div <number1> <number2>')
