#!/bin/zsh

# Description
# git push listed repos
# vsd = ventacity-saas-devel

# Usage
# gg

d1=~/.dotfiles
d2=~/code/shell/scripts
ds=($d1 $d2) 
c1="$(tput setaf 120)"
c2="$(tput setaf 12)"


ecrypt ~/.zprofile ~/.dotfiles/.zprofile_encrypted                       # encrypt zprofile
ecrypt ~/.zsh_a ~/.dotfiles/.zsh_a_encrypted                             # encrypt zsh_a
ecrypt ~/.snowsql/config ~/.dotfiles/.snowsql_config_encrypted           # encrypt snowsql config

for f in ~/macbook_certs/*; do                                           # encrypt vsd certs
    ecrypt $f ~/.dotfiles/mb_certs_encrypted/$(basename $f)
done


for d in $ds; do
    echo "$c1 $d $c2"
    git -C $d add . && 
    git -C $d commit -m "." &&
    git -C $d push -u origin main
done

dcrypt ~/.dotfiles/.zprofile_encrypted ~/.zprofile                       # decrypt zprofile
dcrypt ~/.dotfiles/.zsh_a_encrypted ~/.zsh_a                             # decrypt zsh_a
dcrypt  ~/.dotfiles/.snowsql_config_encrypted ~/.snowsql/config          # decrypt snowsql config

for f in ~/.dotfiles/mb_certs_encrypted/*; do                         # decrypt vsd certs
    dcrypt $f ~/macbook_certs/$(basename $f)
done

cp ~/.zprofile ~/code/zprofile

bat $d2/stuff/reminders.txt;


exit 0
