#!/bin/zsh

# Description
# git push listed repos.  encrypt dotfiles, decrypt
# vsd = ventacity-saas-devel

# Usage
# gg2

d1=~/.dotfiles
d2=~/code/shell/scripts
ds=($d1 $d2) 
c1="$(tput setaf 120)"
c2="$(tput setaf 12)"
g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

# an associative array defining the files to encrypt and their corresponding encrypted names
typeset -A files
files=(
  "~/.zprofile"                    "~/.dotfiles/.zprofile_encrypted"
  "~/.zsh_a"                       "~/.dotfiles/.zsh_a_encrypted"
  "~/.snowsql/config"              "~/.dotfiles/.snowsql_config_encrypted"
)
# encrypt files
for original in "${(@k)files}"; do
  encrypted="${files[$original]}"
  ecrypt "$original" "$encrypted"
  echo "$h encrypted $pg $original $p -> $a $encrypted"
done


for f in ~/macbook_certs/*; do                                           # encrypt vsd certs
    ecrypt $f ~/.dotfiles/mb_certs_encrypted/$(basename $f)
done


for d in $ds; do
    echo "$c1 $d $c2"
    git -C $d add . && 
    git -C $d commit -m "." &&
    git -C $d push -u origin main
done

# decrypt files
for original in "${(@k)files}"; do
  encrypted="${files[$original]}"
  dcrypt "$encrypted" "$original"
  echo "$h decrypted $a $encrypted $p -> $pg $original"
done

for f in ~/.dotfiles/mb_certs_encrypted/*; do                         # decrypt vsd certs
    dcrypt $f ~/macbook_certs/$(basename $f)
done

cp ~/.zprofile ~/code/zprofile

bat $d2/stuff/reminders.txt;


exit 0
