#!/bin/zsh

# Author: James Batman
# Date Created: 12/28/21
# Last Modified: 12/28/21

# Description
# print useful git commands 

# Usage
# githelp

c='\033[1;32m' 
echo ${c}
echo "\t git pull --rebase"
echo
echo "\t git stash"
echo "\t git pull"
echo "\t git stash apply"
echo
echo "\t git checkout -b <branch-name> main"
echo "\t git config pull.rebase false"
echo

exit 0
