#!/bin/zsh

# Author: James Batman
# Date Created: 12/28/21
# Last Modified: 12/28/21

# Description
# print useful git commands 

# Usage
# githelp

c='\033[1;32m' 

echo "${c}
\t git remote show origin
\t git remote add origin
\t git remote --verbose
\t ==================================
\t git pull --rebase
\t git stash
\t git pull
\t git stash apply
\t ==================================
\t git checkout -b <branch-name> main
\t git config pull.rebase false

exit 0
