#!/bin/zsh

# Author: James Batman
# Date Created: 12/09/2021
# Last Modified: 12/09/2021

# Description
# print greek alphabet

# Usage
# greek

c='\033[1;4;33m'
reset='\033[0;32m' 

echo "  
         ${c}                             $reset
         ${c} Α	α       alpha       a $reset
         ${c} Β	β       beta        b $reset
         ${c} Γ	γ       gamma       g $reset
         ${c} Δ	δ       delta       d $reset
         ${c} Ε	ε       epsilon     e $reset
         ${c} Ζ	ζ       zêta        z $reset
         ${c} Η	η       êta         ê $reset
         ${c} Θ	θ       thêta      th $reset
         ${c} Ι	ι       iota        i $reset
         ${c} Κ	κ       kappa       k $reset
         ${c} Λ	λ       lambda      l $reset
         ${c} Μ	μ       mu          m $reset
         ${c} Ν	ν       nu          n $reset
         ${c} Ξ	ξ       xi         ks $reset
         ${c} Ο	ο       omikron     o $reset
         ${c} Π	π       pi          p $reset
         ${c} Ρ	ρ       rho         r $reset
         ${c} Σ	σ       sigma       s $reset
         ${c} Τ	τ       tau         t $reset
         ${c} Υ	υ       upsilon     u $reset
         ${c} Φ	φ       phi         f $reset
         ${c} Χ	χ       chi        ch $reset
         ${c} Ψ	ψ       psi        ps $reset
         ${c} Ω	ω       omega       ô $reset
"

exit 0
