#! python
from sys import argv
from pathlib import Path
from date_utils import get_week
from os import getenv
import subprocess as sp


fname = Path(getenv('PREDOTS')) / 'hours.txt'


def bat():
    sp.run(['bat', fname], capture_output=False, text=True).stdout 


def get_hrs():
    if len(argv) < 2:
        bat()
        exit()
    return argv[1]


def add_hours():
    hrs = get_hrs()
    w   = get_week()
    with open(fname, 'a') as f:
        f.write(w + '\t' + hrs + '\n')


add_hours()
bat()
