#!/bin/zsh

# Description
# Ventacity notes

# Usage
# venh 


c="$(tput setaf 118)"
echo "$c
    teams:
        backend:   Pat (lead), Parker, William
        frontend:  Jason Ives(lead), John Mehta, Joel

    Qs: 
        • requirements: 
            UTM , Ubuntu 20.04 (?), Vue2.x, Vuetify, TypeScript, zsh (ok?)

        • UTM -- mac.getutm.app

              install + setup: 
              https://www.youtube.com/watch?v=hnwK-nkXolc


        • start ~ April 4
"

exit 0
