#!/bin/zsh

# Author: James Batman
# Date Created: 11/29/2021
# Last Modified: 11/29/2021

# Description
# generate a .gitignore file in the current folder 
# for the specified file or project type

# Usage
# ignore <filetype> (ex:  ignore cpp, ignore py) 

case $1 in
    cpp) file=~/.vim/.gitignore.cpp;;
    py) file=~/.vim/.gitignore.py;;
    *) echo "unrecognized filetype.  cannot generate a .gitignore"; exit 1;;
esac

cp $file .gitignore

exit 0
