#! python3

import os
import csv
from colored import fg

blue = fg(87)
red = fg(196)
file = os.path.expanduser('~/code/shell/scripts/stuff/invoices.csv')
fields = []
rows = []


with open(file, 'r') as csvfile:
    reader = csv.reader(csvfile)
    fields = next(reader)

    print()
    for field in fields:
        print(red + field.rjust(20), end='')
    print()
 
    for row in reader:
        for item in row:
            print(blue + item.rjust(20), end='')
        print()

    print() 
