#! python3
import csv
from pathlib import Path
from os import getenv, chdir, getcwd
import subprocess as sp
from datetime import datetime
from colored import fg


blue, orange, yellow, purple, red, grey = fg(122), fg(220), fg(190), fg(200), fg(196), fg(252)
indianred, khaki = fg(202), fg(185)
colors = [ indianred, khaki, orange, blue, red, yellow, purple ]

file = Path(getenv('PREDOTS')) / 'invoices.csv'
sp.run(['clear'])

def print_date():
    s  = datetime.now().strftime(red + '%A  ' + blue + '%B %d, %Y' + khaki + '   %I:%M %p')
    s  = s.replace('PM', 'pm').replace('AM', 'am')
    print('\n\t' + s + '\n')


def company():
    print(yellow + '\t' + 'Ubx Systems Inc' + '\n')


def print_row(t):
    idx = 0
    for item in t:
        print(colors[idx] + item.rjust(15), end='')
        idx = (idx + 1) % len(colors)
    print()


def count_lines():
    with open(file, 'r') as f:
        return sum(1 for _ in f)


print_date()
company()
# N = count_lines()


with open(file, 'r') as f:
    reader = csv.reader(f)
    header = next(reader)
    print_row(header)

    for row in reader:
        print_row(row)

    print() 

