#!/bin/zsh

# Description
# IP & router help 

# Usage
# hip 
c1=$(tput setaf 123)
c2=$(tput setaf 245)
echo "$c1
    ~ sudo ss -ltnp | grep sshd     $c2 # show ports  $c1
    ~ ifconfig
    ~ ipconfig getifaddr en0        $c2 # wi-fi or ethernet IP address  $c1
    ~ netstat -nr | grep default    $c2 # router's internal IP address  $c1
"
exit 0
