#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$x
     zip -r deployment-package.zip .
     zip -g deployment-package.zip crdb_test.py root.crt psycopg2
     p -m pip install --only-binary :all: --platform manylinux1_x86_64  --target ./package -r requirements.txt

$g
  aws lambda delete-function --function-name crdb_test

  aws lambda create-function \\
    --function-name <name> \\
    --region us-west-2  \\
    --zip-file fileb://x.zip  \\
    --handler lambda_function.lambda_handler \\
    --runtime python3.8 \\
    --role <arn>  \\
    --environment \"Variables={PGSSLROOTCERT=./root.crt}\"
"
exit 0
