#!/bin/zsh

# Usage
# leet 


c="$(tput setaf 154)"
echo "$c
    basics:
        Base: Big-O, Recurrence, Mathematical Induction, Hashing
        Methods: Greedy Algorithms, Divide and Conquer, Dynamic Programming
        Analysis of Algorithms: Time Complexity, Asymptotic Notation, 
        Amortization, Recurrence Relations, Probabilistic AlgorithmAnalysis.

    data structures:
        array
        stack
        queue
        linked list
        double linked list
        tree
        binary tree
        binary search tree
        height balanced tree
        hashtable
        heap
        graph

    graph algorithms: 
        DFS, BFS, Shortest Path, Minimum Spanning Tree, Topological Sort
"


exit 0
