#!/bin/zsh

# Description
# IP, VM, linux help

# Usage
# hip 

c="$(tput setaf 226)"
c2="$(tput setaf 252)"

echo "$c
    ~ sudo apt install tasksel
    ~ sudo tasksel install ubuntu-desktop
    ~ sudo apt install spice-vdagent spice-webdavd

    ~ ipconfig getifaddr en0                            $c2# ip address wi-fi or ethernet$c
    ~ ipconfig getifaddr en1                            $c2# ip address wireless$c
    ~ scp -r <dirname> james@192.168.64.2:/home/james

    ~ id -u                                             $c2# UID$c
    ~ sudo adduser <username>                           $c2# creates a new home dir$c
    ~ cat [/etc/group, /etc/passwd]
    ~ which update-rc.d
    ~ crontab -e                                        $c2# edit crontab$c
    ~ crontab -l                                        $c2# list jobs$c

"

exit 0
