#! python
import os
import sys
import subprocess as sp
from webbrowser import open as wbo
from pathlib import Path


links = (
    'https://chatgpt.com/?model=gpt-4o',
    'https://github.com/jwbat',
    'https://www.youtube.com'
)


abs_path = lambda p: Path(p).resolve()


def open_new_browser_window():
    sp.run(['osascript', '-e', 'tell application "Safari" to make new document'])


def open_tabs():
    for url in links:
        wbo(url)


def open_pdf(file_path):
    sp.run(['open', file_path])


open_pdf(abs_path('invoice_70.pdf'))
open_new_browser_window()
open_tabs()
