#!/bin/zsh

# Description
# LS_COLORS codes 

echo " $aqua LS_COLORS $grey
  0 =	Default Colour
  1 =	Bold
  4 =	Underlined
  5 =	Flashing Text
  7 =	Reverse Field
 31 =	Red
 32 =	Green
 33 =	Orange
 34 =	Blue
 35 =	Purple
 36 =	Cyan
 37 =	Grey
 40 =	Black Background
 41 =	Red Background
 42 =	Green Background
 43 =	Orange Background
 44 =	Blue Background
 45 =	Purple Background
 46 =	Cyan Background
 47 =	Grey Background
 90 =	Dark Grey
 91 =	Light Red
 92 =	Light Green
 93 =	Yellow
 94 =	Light Blue
 95 =	Light Purple
 96 =	Turquoise
100 =	Dark Grey Background
101 =	Light Red Background
102 =	Light Green Background
103 =	Yellow Background
104 =	Light Blue Background
105 =	Light Purple Background
106 =	Turquoise Background
"
exit 0
