#!/bin/zsh

c="$(tput setaf 228)"
r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

echo "$x
\t ~ mosquitto -h
\t start script is: ~ mos

\t  restart mosquitto after an upgrade:
\t   ~ brew services restart mosquitto

\t  make changes to the configuration by editing:
\t      /opt/homebrew/etc/mosquitto/mosquitto.conf

\t mosquitto_pub -h 127.0.0.1 -p 1883 -m \"test message\" -t \"sensor/motion\" -d -r 
\t   h = broker address
\t   p = port
\t   m = message
\t   t = topic
\t   d = debug
\t   r = retain

\t mosquitto_sub -h 127.0.0.1  -t \"sensor/motion\" -C 3 -v -d
\t   C = disconnect after 3 msgs
\t   v = display topic
\t   d = debug

"
exit 0
