#!/bin/zsh


r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$r
    #sw-gorge $k
    We’ll be hosting Milesight on March 22 (Friday) in Hood River starting 9am
    (probably up to and including lunch).
    The plan is to rent a waterfront office we’ve been evaluating as a future office for Ventacity:
$gr
        603 Portway Ave, Hood River, OR 97031 $p
        https://maps.app.goo.gl/jMyhT2ukjCqmyetu7
$k
    It’s a very cool place with great views that will help make a good impression.
    Plus we can use it to try out having a workspace where we can have lots of equipment,
    a “living lab” building, and we can all meet and work sometimes.
    There’s an existing large conference table that can fit 15+ people around it.
    We’ll need to bring in chairs the day prior, and I may setup a TV or projector too.
    I’ve told Milesight this is a “temporary office” that we’re evaluating moving into 
    full time since our Portland office may close soon, and since most people live/work in the Gorge.
    I don’t plan to tell them we’re only renting it for 1 day :wink:.
    Anyone in this channel who wants to come in, or can make it into the “office” that day
    is VERY welcome (but we might ask you to bring your own chair! Either Thurs or Fri 8am).
    Kyle will join too and maybe some Corvallis folks(TBD).
    Maybe we’ll also figure out something for a group dinner (just Ventacity, no Milesight)? 
    That part isn’t decided yet, so I’ll have to see what I can finagle and who would want to stick around on a Friday.
    google.comgoogle.com
    603 Portway Ave · 603 Portway Ave, Hood River, OR 97031
    Building
"

exit 0
