#!/bin/zsh

# Description
#  "mtc = mac to conduit"
#  copy dir / file from mac to MultiTech Conduit

# Usage
# mtc

conduit;  # copy pw to clipboard

scp -r $@ admin@192.168.0.55:/opt/lora/mt-app
#scp -r $@ admin@192.168.0.55:/opt/lora/mt-app


exit 0
