#!/bin/zsh

# Description
#  "mtc = mac to conduit"
#  copy dir / file from mac to MultiTech Conduit

# Usage
# mtc [file | dir]


conduit;  # copy pw to clipboard

scp -r $@ admin@192.168.0.55:/opt/lora/mt-iot
#scp -r $@ admin@192.168.0.55:/opt/lora
#scp -r $@ admin@192.168.0.55:/opt/lora/mt-app


exit 0
