#!/bin/zsh

# Description
# mac to linux dir transfer 

# Usage
# mtl <dirname> 

#rsync -rv $1 "james@192.168.64.2:/home/james"

echo $A | pbcopy

rsync -rv $@ "parallels@10.211.55.4:/home/parallels"

exit 0
