#! python3

# Usage
# mult <arg1> <arg2> ... <argN> 

import sys
from math import prod
from colored import fg


color = fg(214)

try:
    ans = prod([float(x) for x in sys.argv[1:]])
    print('\t\t\t' + color + str(ans))

except:
    print('usage: mult <number1> <number2> ...')
