#!/bin/zsh

# Author: James Batman
# Date Created: 12/15/21
# Last Modified: 12/15/21

# Description
# multiply numbers
#  - uses c++ binary mult2 in /usr/local/bin

# Usage
# mult <arg1> <arg2> ... <argN> 

c=$(tput setaf 214)

echo "\t\t\t" $c $(mult2 $@)


exit 0
