#! python3

import os
import sys
import json
import datetime as dt
#from datetime import date
from newsapi import NewsApiClient
from colored import fg


#key = os.environ['newsapikey']
key = os.getenv('newsapikey')
newsapi = NewsApiClient(api_key=key)

topics = ['UFO', 'UAP']
blue = fg(122)
orange = fg(220)
grey = fg(250)
justify = 15


if len(sys.argv) == 2:
    try:
        delta = int(sys.argv[1])
        from_date = (dt.datetime.now() - dt.timedelta(days = delta)).strftime('%Y-%m-%d')
    except:
        print('argument must be an integer')
        exit()
else:
    from_date = (dt.datetime.now()).strftime('%Y-%m-%d')

data = newsapi.get_everything(q = 'UFO',
                              from_param = from_date,
                              language = 'en',
                              sort_by = 'relevancy')

for article in data['articles']:
    if any(t in article['title'] for t in topics):
        print(blue + 'title: '.rjust(justify), orange + article['title'][:100])
        print(blue + 'url: '.rjust(justify), grey + article['url'])
        print(blue + 'description: '.rjust(justify), grey + article['description'][:100] + '...')
        print()
