#!/bin/zsh

# Author: James Batman
# Date Created: 12/15/2021
# Last Modified: 12/15/2021

# Description
# Prints to the terminal the values of pi, e, √2, and φ (phi, the golden ratio) to the 
#  provided number of decimal places up to 1000.

# Usage
# nrs [nr_of_decimals] 

col='\033[0;37m'

echo ""
echo "${col}      π: $( pi $1 )"
echo "${col}      e: $( e $1 )"
echo "${col}     √2: $( sqrt2 $1 )"
echo "${col}      φ: $( phi $1 )"
echo ""

exit 0
