#!/bin/zsh

# Author: James Batman
# Date Created: 12/15/2021
# Last Modified: 01/02/2022

# Description

#  print the values of pi, e, φ (phi, the golden ratio), 
#    and √2 to n-decimal places.

# Usage
# nrs <nr_of_decimal_places>  (default=80, max=1000) 

c1="$(tput setaf 228)"

param=$1
digits=${param:-80}

echo " $c1      
\t  π:  $( pi $digits )

\t  e:  $( e $digits )

\t  φ:  $( phi $digits )

\t √2:  $( sqrt2 $digits )
"

exit 0
