#!/bin/zsh

# Author: James Batman
# Date Created: 12/15/2021
# Last Modified: 01/02/2022

# Description

#  print the values of pi, e, φ (phi, the golden ratio), 
#    and √2 to n-decimal places.

# Usage
# nrs <nr_of_decimal_places>  (default=80, max=1000) 

c1="$(tput setaf 214)"
c2="$(tput setaf 83)"

param=$1
digits=${param:-80}

echo
echo "$c1      π:  $( pi $digits )"
echo 
echo "$c1      e:  $( e $digits )"
echo
echo "$c1      φ:  $( phi $digits )"
echo
echo "$c1     √2:  $( sqrt2 $digits )"
echo
exit 0
