#!/bin/zsh

# Description
# nvm help 

# Usage
# hnvm

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki; c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink;

clear;

echo "$pg
      nvm ls
      nvm ls-remote
      nvm use <version> 
      sudo rm -R ~                         $x /.npm ~/.nvm  // remove before re-install  $pg
      nvm cache clear                      $x free up disk space or troubleshoot node issues

$g      nvm install node       $x               Install the latest available version
$g      nvm use node           $x               Use the latest version
$g      nvm install --lts      $x               Install the latest LTS version
$g      nvm use --lts          $x               Use the latest LTS version
$g      nvm use 18.18.0        $x               

"
exit 0
