#!/bin/zsh


r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

echo "$x flags returned by netstat $h
    U: $x the route is up and can be used. $h
    H: $x the destination is a host (as opposed to a network). $h
    L: $x the route is a local (loopback) route. $h
    G: $x the route uses a gateway. $h
    W: $x the route is a wildcard route. $h
    I: $x the route is an ICMP redirect. $h
    R: $x the route was dynamically created by a routing protocol. $h
    D: $x the route was created by a redirect. $h
    A: $x the route is authoritative (i.e., added manually, not by a routing protocol). $h

  netstat $x 
    This command is used to display active network connections, as well as various
    statistics about network traffic on a computer. It can be used to troubleshoot network issues
    and identify potential security risks. $s

  nmap $x 
    This command is a network exploration and security auditing tool.
    It can be used to scan networks to identify hosts and services,
    and can also be used to test the security of networked systems by identifying open ports and vulnerabilities. $s

  ifconfig $x 
    This command is used to display information about network interfaces (such as Ethernet or Wi-Fi)
    on a computer. It can be used to configure and troubleshoot network settings, such as IP addresses and network masks. $s

  ipconfig $x 
    This command is similar to ifconfig, but is used specifically on Windows operating systems to display
    information about network interfaces and configure network settings. It can be used to view IP addresses,
    subnet masks, and other network configuration information.

    ~ networksetup -listallnetworkservices $x
    ~ sudo networksetup -getinfo \"AX88179A\" $x
    ~ netstat -nr $s

    ~ ipconfig getifaddr en0    $x get IP address of Macbook $s
    ~ ipconfig getpacket en0    $x display the DHCP lease information for the en0 interface,
                                   usually the primary network interface on a MacBook.
                                   If connected to a different network interface, replace
                                   \"en0\" with that interface name, e.g. en1, en2, etc. $r

    ~ netstat -nr | grep 192 | grep :
    ~ arp -a                    $x address resolution protocol (map IP to MAC address) $r

    ~ ping 192.168.1.255        $x send a ping request to the broadcast address of your subnet. 
                                 all devices on subnet 192.168.1.x will respond $r
    ~ arp -a                    $x list devices on network that responded to the ping,
                                 with their IPs and MAC addresses.
"

exit 0
