#!/bin/zsh

# Author: James Batman
# Date Created: 
# Last Modified: 

# Description
# 

# Usage
# 

osascript -e "
      tell application \"iTerm2\"
        set newTab to (create tab with default profile)
        tell current session of newTab
            write text \"env \"
        end tell
      end tell
    "


exit 0
