#! python
import os
from sys import argv
import subprocess as sp
from webbrowser import open as wbo
from pathlib import Path
from os import getenv


getpath = lambda s: Path(getenv(s))
pdf_dir = getpath('PDFS')
srcs    = Path('sources.txt')     # optional
urls    = []
pdfs    = []


def read_sources():
    with open(srcs, 'r') as f:
        return [line.strip() for line in f.readlines()]


def sort_paths(paths):
    for path in paths:
        if path.startswith('htt'):
            urls.append(path)
        elif path.endswith('pdf'):
            pdfs.append(str(pdf_dir / path))


if srcs.exists():
    sort_paths(read_sources())
else:
    sort_paths(argv[1:])


def open_new_browser_window():
    sp.run(['osascript', '-e', 'tell application "Safari" to make new document'])


def open_tabs():
    for url in urls:
        wbo(url)


def open_pdfs():
    for path in pdfs:
        sp.run(['open', path])


open_new_browser_window()
open_tabs()
open_pdfs()
