#! python
import os
from sys import argv
import subprocess as sp
from webbrowser import open as wbo
from pathlib import Path
from os import getenv


sources = 'sources.txt'
getpath = lambda s: Path(getenv(s))
pdf_dir = getpath('PDFS')
srcs    = Path(sources)     # optional
args    = argv[1:] if len(argv) > 1 else None
urls    = []
pdfs    = []


def read_sources():
    with open(srcs, 'r') as f:
        return [line.strip() for line in f.readlines()]


def sort_paths(paths):
    for path in paths:
        if path.startswith('htt'):
            urls.append(path)
        elif path.endswith('pdf'):
            pdfs.append(str(pdf_dir / path))


if args:
    sort_paths(args)
elif srcs.exists():
    sort_paths(read_sources())
else:
    print('no args or sources.txt were provided')


def open_new_browser_window():
    sp.run(['osascript', '-e', 'tell application "Safari" to make new document'], stdout=sp.DEVNULL)


def open_browser_tabs():
    for url in urls:
        try:
            wbo(url)
        except Exception as e:
            print(f'exception while opening {url}: {e}')


def open_pdfs():
    for path in pdfs:
        try:
            sp.run(['open', path])
        except Exception as e:
            print(f'exception while opening {path}: {e}')


open_new_browser_window()
open_browser_tabs()
open_pdfs()
