#!/bin/zsh

# Author: James Batman
# Date Created: 12/23/2021
# Last Modified: 12/31/2021

# Description
# print powers of 2
# depends on a c++ binary, pow2

# Usage
# p2  

c=$(tput setaf 50)

echo "$c\n$(powers2) \n"

exit 0
