#! python
import os
import json
from random import randint
from colored import fg
from sys import argv


dir_path     = os.path.expanduser('~')
fname        = 'words.json'
file_path    = os.path.join(dir_path, fname)
color_codes  = [221, 157, 160, 6, 9, 209]
randcolor    = lambda : fg(color_codes[randint(0, len(color_codes) - 1)])
pprint       = lambda s: print(randcolor() + s.rjust(25))

with open(file_path, 'r') as f:
    d = json.load(f)


def solve(ltrs):
    for word in d:
        s1 = set(list(ltrs))
        s2 = set(list(word))
        if s1 == s2:
            pprint(word)


print()
pprint('~' * 8)
solve(argv[1])
pprint('~' * 8)
print()
