#! python
import json
from sys import argv
from os.path import expanduser, join
from random import randint
from colored import fg


DIR          = expanduser('~')
FNAME        = 'words_alpha.txt'
fpath        = join(DIR, FNAME)

color_codes  = [221, 157, 160, 6, 9, 209]
randcolor    = lambda : fg(color_codes[randint(0, len(color_codes) - 1)])
pprint       = lambda s: print(randcolor() + s.rjust(25))


def decor(f):
    def g(*args):
        print()
        pprint('~' * 12)
        f(*args)
        pprint('~' * 12)
        print()
    return g


@decor
def solve(ltrs):
    with open(fpath, 'r') as f:
        for line in f:
            word = line.strip()
            if set(ltrs) == set(word):
                pprint(word)


solve(argv[1])
