#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 63)"

echo "
\t $h GATEWAY_EUI :          $y $GATEWAY_EUI
\t $h Push Button DevEui :   $y $PB_DEVEUI
"

exit 0
