#!/bin/zsh

# Author: James Batman
# Date Created: 11/12/21
# Last Modified: 11/12/21

# Description
# Prints to the terminal φ, the golden ratio, to the provided number
#  of decimal places (default=50) up to 10000.

# Usage
# phi [number_of_decimal_places]

phi=$(<~/code/shell/scripts/stuff/phi.txt)


c="$(tput setaf 228)"
param=$1
nr_of_digits=${param:-50}

echo "$c ${phi:0:$((2 + $nr_of_digits))}"

exit 0
