#!/bin/zsh

# Author: James Batman
# Date Created: 11/12/21
# Last Modified: 11/12/21

# Description
# Prints to the terminal pi to the provided number of 
# decimal places (default = 50) up to 10000

# Usage
# pi [optional: number_of_decimals_places]


pi=$(<~/code/shell/scripts/stuff/pi.txt)

purple='\033[0;35m'
param=$1
nr_of_digits=${param:-50}

echo "${purple} ${pi:0:$((2 + $nr_of_digits))}"

exit 0
