#!/bin/zsh

# Author: James Batman
# Date Created: 12/06/2021
# Last Modified: 12/13/2021

# Description
# git pull the listed repos

# Usage
# pll

d1=~/.dotfiles
d2=~/code/shell/scripts
d3=~/code/cpp/utilities
d4=~/code/cpp/functional_cpp
d5=~/code/cpp/idioms
d6=~/code/cpp/experimental
d7=~/code/cpp/courses/numerical

ds=($d1 $d2 $d3 $d4 $d5 $d6 $d7)

for d in $ds; do
    git -C $d pull
done

exit 0
