#!/bin/zsh

# Description
# git pull listed repos

# Usage
# pll

d1=~/.dotfiles
d2=~/code/shell/scripts
d3=~/code/cpp/utilities
d4=~/code/cpp/functional
d5=~/code/cpp/idioms
d6=~/code/cpp/experimental
d7=~/code/cpp/courses/design_patterns
d8=~/code/cpp/sdl
d09=~/code/python/scipy
d10=~/code/samples

ds=($d1 $d2 $d3 $d4 $d5 $d6 $d7 $d8 $d09 $d10)

for d in $ds; do
    git -C $d pull --rebase
done

exit 0
