#!/bin/zsh

# Description
# git pull listed repos

# Usage
# pll

d1=~/.dotfiles
d2=~/code/shell/scripts

ds=($d1 $d2)

c1="$(tput setaf 120)"
c2="$(tput setaf 12)"

for d in $ds; do
    echo "$c1 $d $c2"
    git -C $d pull --rebase
done

exit 0
