#!/bin/zsh

# Author: James Batman
# Date Created: 12/05/2021
# Last Modified: 12/05/2021

# Description
# print the result of arg1 ^ arg2 

# Usage
# pow <arg1> <arg2> 

c='\033[1;31m' 

echo ""
echo -en $c  '\t'
echo  $1 ^ $2 | bc
echo ""

exit 0
