#!/bin/zsh

# Author: James Batman
# Date Created: 12/05/2021
# Last Modified: 12/16/2021

# Description
# print the result of arg1 ^ arg2;
#  args may be either a float or a fraction;
#  e.g., pow 8 1/3  -->  2
#        pow 9 0.5  -->  3
# calls a c++ binary, pow2

# Usage
# pow <arg1> <arg2>   

c='\033[1;32m' 

echo
echo -en $c  '\t'
echo  $(pow2 $1 $2 )
echo


exit 0
