#!/bin/zsh

# Author: James Batman
# Date Created: 12/05/2021
# Last Modified: 12/16/2021

# Description
#   print the result of arg1 ^ arg2;
#    args may take the form of a float or a fraction:
#             pow 8 1/3    -->  2
#             pow 9 0.5    -->  3
#   calls the c++ binary, pow2

# Usage
# pow <arg1> <arg2>   

c=$(tput setaf 80)

echo "\n $c $(pow2 $1 $2)"
echo

exit 0
