#! python3
import sys
import subprocess as sp


try:
    file = sys.argv[1]
    p1 = sp.run(['cat', file], capture_output=True, text=True)
    print(p1.stdout)
except:
    print('usage:  p.py <filename>')

