#! python3

import sys
import subprocess as sp
from colored import fg

color = fg(190)
print(color)

try:
    file = sys.argv[1]
    p1 = sp.run(['bat', file], capture_output=True, text=True)
    print(p1.stdout)
except:
    print('usage:  printfile <filename>')
