#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;
z="$(tput setaf 63)"

clear;

echo " $c
    HC options for adding Notes to a Linegraph: $z
      https://www.highcharts.com/docs/advanced-chart-features/annotations-module
      https://www.highcharts.com/docs/stock/flag-series
$x
      Can we have a Note attached that looks like an Annotation?
      (shows at least some of the Note text, perhaps with a “…”) and 
      where the user can hover/click to expand to read the full Note.
$c
    Some annotations (when they are specific to that Property) would make sense attached to the Linegraph $k
      Others (like when we show Journal events that might be related to the Property)
      might be better shown on the X-axis (is that an option with Annotations? or just Flags?)
$c
    What is the best way to capture user clicks on the Linegraph to add a text Annotation (Note)? $k
      What is the HC mechanism to do this or intercept such an event?
      Is there any reason to consider allowing  X-axis Annoations/Flags?
$c
    Generally, some brainstorming on how these Notes related to the Journal and the Assets that they are attached to $k
      Example:$x Any time someone changes a config setting on an HVAC machine,
               that event should appear on any Linegraphs that related to indoor comfort and air quality.
               Should we put an X-axis Flag on every Linegraph that could be relevant (all IAQ sensors, all variables)? $k
      What are some other use cases for Notes as they related to Journal and various Asset Properties?
$pg
    How do we handle attaching a Note to time series data when the 
    Snowflake Aggregation Window (MIN/MAX/AVG) changes dynamically
    based on the size of the Navigator View Window (Start/End Times)?

    Can you make any sort of visual marker appear in the Navigator?
"
exit 0
