#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;
clear;

echo " $a
    We get requests (Aubrey and ESCO so far) for the ability to
    compare one sensor to another (usually an outdoor air temp sensor against an interior or HVAC sensor).
    I’m contemplating a “Compare to…” option on each HC Linegraph that would let you pick any other
    like Property (Temp vs Temp, RH vs RX) and turn the HC into a dual line graph
    (not dual Y-axis for now, hence property req)

    It’ll need some interactive dialog to find the Property of interest:
    Building -> SmartAsset -> Property list
     (current Building)

    let’s make the MVP that it’s only the Current Building and we’ll worry about adding that feature later
    (Building selection within the account)
"

exit 0
