#!/bin/zsh

# Description
# pyenv & python help 

# Usage
# pyh 

echo "
\t $gold brew install pyenv     $sea  (edit .zprofile, .zshrc; see: towardsdatascience)
\t $gold pyenv install -l       $sea  (see available versions)
\t $gold pyenv install 3.10.3
\t $gold pyenv global 3.10.3    $sea  (make version available everywhere)
\t $gold pyenv local 3.10.3     $sea  (make only current directory use this version)
\t $gold python pgm.py          $sea  (use the enabled version of python)
"


exit 0
