#! python3

from colored import fg

c0 = fg(184)
c1 = fg(183)
c2 = fg(86)
c3 = fg(45)
c4 = fg(164)

q1 = c0 + "\
\t Files are a means to store data in a storage device."

q2 = c1 + "\
\t An object is a region of storage that has a type and a value."

q3 = c3 + "\
\n\t An expression is referentially transparent if it has no observable side effects,\
\n\t and therefore all functions used in that expression are pure.\
\n\t  - Ivan Cukic"

q4 = c4 + "\
\t For what shall it profit a man, \n
\t if he shall gain the whole world but lose his soul?"

q5 = c2 + "\n
\t You can't make somebody understand something if their salary \n
\t depends upon them not understanding it.  \n
\t  - Upton Sinclair"

q6 = c3 + "\n
\t Any fool can write code that a computer can understand. \n
\t Good programmers write code that humans can understand. \n - Martin Fowler"

q7 = c1 + "\n
\t When clients of a complex system are ignorant of how it works, \n
\t yet happy with what it does, that says a lot about the design of the system. \n
\t  - Scott Meyers"


qs = [q1, q2, q3, q4, q5, q6, q7]

for q in qs:
    print("\n" + q)
