#!/bin/zsh

# Author: James Batman
# Date Created: 12/01/2021
# Last Modified: 01/02/2022

# Description
# Quotes of Beauty 

# Usage
# quotes 

#autoload colors; colors
#$fg[green]text$reset_color
c0="$(tput setaf 184)"
c1="$(tput setaf 183)"
c2="$(tput setaf 86)"
c3="$(tput setaf 45)"
c4="$(tput setaf 164)"

q1="$c0   Files are a means to store data in a storage device."
q2="$c1   An object is a region of storage that has a type and a value."
q3="$c3   An expression is referentially transparent if it has no observable
   side effects, and therefore all functions used in that expression
   are pure. 
   - Ivan Cukic"
q4="$c4   For what shall it profit a man,
   if he shall gain the whole world but lose his soul?"
q5="$c2   You can't make somebody understand something if their salary
   depends upon them not understanding it. 
    - Upton Sinclair"
q6="$c3   Any fool can write code that a computer can understand. 
   Good programmers write code that humans can understand. 
    - Martin Fowler"
q7="$c1   When clients of a complex system are ignorant of how it works,
   yet happy with what it does, that says a lot about the design of the system. 
    - Scott Meyers"
q8="$c4   There is a wise passivity that enables things to come about less by
   what is done than by what is not done, that opens up possibility where
   activity closes it donw. 
    - Iain McGilchrist"


qs=($q1 $q2 $q3 $q4 $q5 $q6 $q7 $q8)

for q in $qs; do
   echo ""
   echo $q
done

echo ""
exit 0
