#!/bin/zsh

# Author: James Batman
# Date Created: 12/01/2021
# Last Modified: 12/01/2021

# Description
# Quotes of Beauty 

# Usage
# quotes 

autoload colors; colors
#$fg[green]text$reset_color
purple='\033[0;35m'

echo
echo $fg[white] "  An object is a region of storage that has a type and a value."
echo
echo $purple "  An object is a region of storage that has a type and a value."
echo
echo $fg[green]"   An expression is referentially transparent if it has no observable
   side effects, and therefore all functions used in that expression
   are pure." - Ivan Cukic
echo
echo $fg[yellow] "  For what shall it profit a man,
   if he shall gain the whole world but lose his soul?"
echo

exit 0
