#!/bin/zsh

# Author: James Batman
# Date Created: 12/01/2021
# Last Modified: 12/01/2021

# Description
# Quotes of Beauty 

# Usage
# quotes 

#autoload colors; colors
#$fg[green]text$reset_color
c1='\033[0;35m'
c2='\033[0;35m'
c3='\033[0;35m'

echo
echo "$c1   Files are a means to store data in a storage device."
echo
echo "$c2   An object is a region of storage that has a type and a value."
echo
echo "$c3   An expression is referentially transparent if it has no observable
   side effects, and therefore all functions used in that expression
   are pure." - Ivan Cukic
echo
echo "$c1   For what shall it profit a man,
   if he shall gain the whole world but lose his soul?"
echo

exit 0
