#!/bin/zsh

# Author: James Batman
# Date Created: 12/04/2021
# Last Modified: 12/16/2021

# Description
# print n-digit random integer 
#  **note: depends on c++ binary, random2

# Usage
# random <n> 

color='\033[1;32m'

echo ""
echo "${color}$( random2 $1 )"
echo ""

exit 0
