#!/bin/zsh

# Author: James Batman
# Date Created: 12/04/2021
# Last Modified: 12/16/2021

# Description
# print n-digit random integer 
#  depends on c++ binary, random2

# Usage
# random <n> 

c="$(tput setaf 83)"

echo
echo "$c $(random2 $1)"
echo

exit 0
