#!/bin/zsh

# Description
# 

# Usage
# 

x="dbvgmnp"  # options
color="$(tput setaf 226)"

show_options() {
   echo "$color
        options are one of [ $x ] :
            devhints.io,
            bash,
            vimscript,
            git,
            matplotlib,
            numpy,
            pandas
        "
}

while getopts $x opt; do
    case $opt in
        d) open 'https://devhints.io';; # all
        b) open 'https://devhints.io/bash';;
        v) open 'https://devhints.io/vimscript';;
        g) open ~/code/shell/scripts/stuff/cheatsheets/git.pdf;;
        m) open ~/code/shell/scripts/stuff/cheatsheets/matplotlib.pdf;;
        n) open ~/code/shell/scripts/stuff/cheatsheets/numpy.pdf;;
        p) open ~/code/shell/scripts/stuff/cheatsheets/pandas.pdf;;
        *) show_options;;
    esac
done






exit 0
