#!/bin/zsh

# Author: James Batman
# Date Created: 11/12/21
# Last Modified: 01/02/21

# Description
# show useful shell commands

# Usage
# show

c1="$(tput setaf 83)"
c2="$(tput setaf 251)"

echo $c1
echo "\t grep -rn --exclude-dir=.git "chrono" .     \t $c2 -r recursive"  $c1
echo "\t find . -maxdepth 1 -type l -ls             \t $c2 list symlinks"  $c1
echo "\t ln -s /path/to/original /path/to/symlink   \t $c2 create symlink"  $c1
echo "\t rm /path/to/symlink                        \t $c2 remove symlink"  $c1
echo "\t man zshmisc                                \t $c2 prompt sequences"  $c1
echo "\t sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist   generate locate db"  $c1
echo
echo "\t ls | wc -l         \t $c2 count nr of files in present directory"  $c1
echo "\t print -l *(.)      \t $c2 print all files in directory"  $c1
echo "\t text=\$(<file.txt) \t $c2 read each line of file.txt into array"  $c1
echo "\t cal -A 1           \t $c2 calendar"  $c1
echo "\t \$TERM             \t $c2 terminal colors"  $c1
echo "\t env                \t $c2 environment variables"  $c1
echo "\t export             \t $c2 list environment variables and their values"  $c1
echo "\t set                \t $c2 also list shell variables"  $c1
echo "\t uname -m           \t $c2 processor architecture"  $c1
echo "\t uname -o           \t $c2 name of operating system"  $c1
echo "\t sw_vers            \t $c2 OS version info"  $c1
echo "\t fc -l -10          \t $c2 list the last 10 commands in history"  $c1
echo "\t print \${#string}  \t $c2 count character in string"  $c1
echo "\t print \${(w)#string}\t $c2 count words in string"  $c1
echo 
echo "\t rsync -av --dry-run --exclude 'liu' ventacity/ /Volumes/mu/ven/"  $c1
echo "\t grep -rl --exclude-dir=node_modules '\$t' ."  $c1
echo 

exit 0
