#!/bin/zsh

set -o errexit      # stop script immediately upon error
set -o nounset      # treat unset variables as an error
set -o pipefail     # consider any part of a pipe failing as an error

c="$(tput setaf 226)"
first_arg="${1:-defaultvalue}"
echo "$c
\t $first_arg
\t==="

for arg in "$@"; do
  echo "\t $arg"
  shift
done

exit 0
