#!/bin/zsh

# Author: James Batman
# Date Created: 11/12/21
# Last Modified: 11/12/21

# Description
# Prints to the terminal the value of √2 to the provided number of decimal 
#  places (default=50) up to 10000.

# Usage
# sqrt2 [number_of_decimal_places]


sqrt=$(<~/code/shell/scripts/stuff/sqrt2.txt)


c="$(tput setaf 83)"
param=$1
nr_of_digits=${param:-50}
echo "$c ${sqrt:0:$((2 + nr_of_digits))}"


exit 0
