#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$h
  				Suriname
$gr
        - [$y X$gr ] What is the exchange rate? $y 1 USD = 21 SRD $gr
        - [$y X$gr ] Order a guidebook for Suriname.$y Suriname (Bradt Travel Guide), Briggs, Philip (AMZ) $gr
        - [$y X$gr ] What are the top two digital nomad websites? $y - $gr
        - [$y X$gr ] Use booking.com to check out lodging in Paramaribo. $y \$10 - \$80 $gr
        - [$y X$gr ] Skyscanner.com flights. $y \$984 RT / Dec. 1 - Jan. 11 $gr
"

exit 0
