#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$h
    °C       °F     
    ==      ====    $pg
    17      62.6
    18      64.4
    19      66.2
    20      68.0
    21      69.8
    22      71.6
    23      73.4
    24      75.2
"

exit 0
