#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$h
     F           C    $pg
    65          18.3
    66          18.9
    67          19.4
    68          20.0
    69          20.6
    70          21.1
    71          21.7
    72          22.2
    73          22.8
    74          23.3
    75          23.9
    76          24.4
"

exit 0
