#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$h
     C           F       F rnd $pg
   20.0        68.0       68
   20.5        68.9       69
   21.0        69.8       70
   21.5        70.7       71
   22.0        71.6       72
   22.5        72.5       72
   23.0        73.4       73
   23.5        74.3       74
   24.0        75.2       75
   24.5        76.1       76
"

exit 0
