#!/bin/zsh

# Description
# todo list 

# Usage
# todo 

c="$(tput setaf 157)"

echo "$c
    •  bash: --verbose-arg
    ==============================================
    •  install terminal emulator in Linux
    ==============================================
    •  learn about arm64 architecture.
"

exit 0
