#!/bin/zsh

# Description
# todo list 

# Usage
# todo 

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

echo "k
$x    ==============================================
$s        JOIN sql
$x    ==============================================
"

exit 0
