#!/bin/zsh

grey=$(ts 252)
lightblue=$(ts 153)
gold=$(ts 220)
pale=$(ts 242)
salmon=$(ts 216)

echo "
$salmon ---------------------------------------------------------------------------------------------------------------

$grey 
\t # UUID's created via PSQL's gen_random_uuid() $lightblue

\t site_uuid     = '9f02171a-32a0-4695-a7f2-aad43528af58'
\t device_A_uuid = 'a2204077-054e-49f3-ba0c-17a34cd01800'  $grey# Phase-A-DA9D $lightblue
\t device_B_uuid = '7b794dd5-e29c-4851-a533-100c57dc4cff'  $grey# Phase-B-0673 $lightblue
\t device_C_uuid = 'ef66fc2c-3c42-458c-abc7-cbfe9aca52ac'  $grey# Phase-C-8DFB $lightblue

$salmon ---------------------------------------------------------------------------------------------------------------

\t SQL

$salmon ---------------------------------------------------------------------------------------------------------------

9f02171a-32a0-4695-a7f2-aad43528af58,
a2204077-054e-49f3-ba0c-17a34cd01800,
2022-07-01T20:00:00.0000000Z,
VU-HOTDROP,
1,
\"{
    \"\"rssi\"\": -54.0,
    \"\"accumulated_nanoampere_hour\"\": 14166378032,
    \"\"minimum_milliampere\"\": 0,
    \"\"average_milliampere\"\": 0,
    \"\"maximum_milliampere\"\": 0,
    \"\"supply_voltage\"\": 5,
    \"\"temperature_celsius\"\": 24
  }\",
2000-01-01T20:00:00.0000000Z,deviaqpro

$gold ---------------------------------------------------------------------------------------------------------------

kWh = (Ah * V) / 1000

$salmon
select STAMP, data:\"accumulated_nanoampere_hour\" as NA, data:\"supply_voltage\" from \"SBG\".\"SBG_STATE_TRANSFER\" 
where DEVICEUUID='7b794dd5-e29c-4851-a533-100c57dc4cff'
  and SITEUUID='9f02171a-32a0-4695-a7f2-aad43528af58'      
  and data:\"accumulated_nanoampere_hour\" in (
    select max(data:\"accumulated_nanoampere_hour\") from \"SBG\".\"SBG_STATE_TRANSFER\" 
    group by DEVICEUUID, date(STAMP)
  ) 
order by STAMP asc;
"


exit 0
