#!/bin/zsh

grey=$(ts 252)
lightblue=$(ts 153)
gold=$(ts 220)
pale=$(ts 242)
salmon=$(ts 216)

echo "
$salmon ---------------------------------------------------------------------------------------------------------------

$grey 
\t # UUID's created via PSQL's gen_random_uuid() $lightblue

\t site_uuid     = '9f02171a-32a0-4695-a7f2-aad43528af58'
\t device_A_uuid = 'a2204077-054e-49f3-ba0c-17a34cd01800'  $grey# Phase-A-DA9D $lightblue
\t device_B_uuid = '7b794dd5-e29c-4851-a533-100c57dc4cff'  $grey# Phase-B-0673 $lightblue
\t device_C_uuid = 'ef66fc2c-3c42-458c-abc7-cbfe9aca52ac'  $grey# Phase-C-8DFB $lightblue

$salmon ---------------------------------------------------------------------------------------------------------------

\t SQL
$grey 
\t table columns: $lightblue 
\t SITEUUID, DEVICEUUID, STAMP, DEVICE_TYPE, DEVICE_ID, DATA, DATECREATED, SERVER_SOURCE

$grey 
\t query: $lightblue
\t select date(STAMP), count(*), SITEUUID, DEVICEUUID, DEVICE_TYPE from \"SBG\".\"SBG_STATE_TRANSFER\"
\t where DEVICE_TYPE = 'VU-HOTDROP' and SITEUUID = '9f02171a-32a0-4695-a7f2-aad43528af58'
\t group by date(STAMP), DEVICEUUID, DEVICE_TYPE, SITEUUID
\t order by DEVICEUUID, date(STAMP);

$salmon ---------------------------------------------------------------------------------------------------------------

9f02171a-32a0-4695-a7f2-aad43528af58,
a2204077-054e-49f3-ba0c-17a34cd01800,
2022-07-01T20:00:00.0000000Z,
VU-HOTDROP,
1,
\"{
    \"\"rssi\"\": -54.0,
    \"\"accumulated_nanoampere_hour\"\": 14166378032,
    \"\"minimum_milliampere\"\": 0,
    \"\"average_milliampere\"\": 0,
    \"\"maximum_milliampere\"\": 0,
    \"\"supply_voltage\"\": 5,
    \"\"temperature_celsius\"\": 24
  }\",
2000-01-01T20:00:00.0000000Z,deviaqpro

$gold ---------------------------------------------------------------------------------------------------------------
{ 
    accumulated_nanoampere_hour: 14166378032,
    average_milliampere: 0,
    maximum_milliampere: 0,
    minimum_milliampere: 0,
    rssi: -54,
    supply_voltage: 5,
    temperature_celsius: 24 
}

kWh = (Ah * V) / 1000
"


exit 0
