#!/bin/zsh

red=$(ts 160)
grey=$(ts 252)
lightblue=$(ts 153)
gold=$(ts 220)
pale=$(ts 242)
salmon=$(ts 216)
honeydew=$(ts 194)


echo "
$salmon ---------------------------------------------------------------------------------------------------------------

$grey 
\t # UUID's created via PSQL's gen_random_uuid() $lightblue

   site_uuid     = '9f02171a-32a0-4695-a7f2-aad43528af58'
   device_A_uuid = 'a2204077-054e-49f3-ba0c-17a34cd01800'  $grey# Phase-A-DA9D $lightblue
   device_B_uuid = '7b794dd5-e29c-4851-a533-100c57dc4cff'  $grey# Phase-B-0673 $lightblue
   device_C_uuid = 'ef66fc2c-3c42-458c-abc7-cbfe9aca52ac'  $grey# Phase-C-8DFB $lightblue
$yellow
   kWh = (Ah * V) / 1000

$honeydew======================================================================================================================
$grey # SQL  $gold
select STAMP, data:\"accumulated_nanoampere_hour\" as NA, data:\"supply_voltage\" from \"SBG\".\"SBG_STATE_TRANSFER\" 
where DEVICEUUID='7b794dd5-e29c-4851-a533-100c57dc4cff'
  and SITEUUID='9f02171a-32a0-4695-a7f2-aad43528af58'      
  and data:\"accumulated_nanoampere_hour\" in (
    select max(data:\"accumulated_nanoampere_hour\") from \"SBG\".\"SBG_STATE_TRANSFER\" 
    group by DEVICEUUID, date(STAMP)
  ) 
order by STAMP asc;

$honeydew======================================================================================================================

$grey# deviceUuid: "ef66fc2c-3c42-458c-abc7-cbfe9aca52ac"
$grey# deviceUuid: "7b794dd5-e29c-4851-a533-100c57dc4cff" $gold
query Energy {
  energyConsumptionByTime(
    siteUuid: "9f02171a-32a0-4695-a7f2-aad43528af58",
    deviceUuid: "7b794dd5-e29c-4851-a533-100c57dc4cff",
    startDate: "2022-07-19",
    endDate: "2022-08-18") {
    points {
      time
      kWh
    }
  }
}

$grey # response $red
{
  "data": {
    "energyConsumptionByTime": {
      "points": [
        {
          "time": "2022-07-20",
          "kWh": 2.4594677204760003
        },
        {
          "time": "2022-07-21",
          "kWh": 2.4985617582510002
        },
        {
          "time": "2022-07-22",
          "kWh": 2.567383510419
        },
        {
          "time": "2022-07-23",
          "kWh": 3.7647126114389997
        },
        {
          "time": "2022-07-24",
          "kWh": 3.7771321657679997
        },
        {
          "time": "2022-07-25",
          "kWh": 3.801284203275
        },
        {
          "time": "2022-07-26",
          "kWh": 3.8259886463369996
        },
        ...

[[ \"2022-07-20\", 2.4594677204760003 ],
[ \"2022-07-21\", 2.4985617582510002 ],
[ \"2022-07-22\", 2.567383510419 ], ...]

"


exit 0
