#!/bin/zsh

# Description
#  

# Usage
# sbgh
c="$(tput setaf 196)"

echo "$c
    ~ npm install node-sass@npm:sass

    sbg-webapp/modules/vue-ui/src/vs/views/DeviceView.vue

    site-health-report
    ~ git checkout site-health-report
    ~ git branch -r

    ~ git commit -m 'msg' --no-verify
     
    ~ npm run lint --fix

    http://localhost:8801/
    http://localhost:8090/new/vs/device/e117654c-f89f-46b4-a32a-8bd1d24c2d7b
    http://localhost:8090/new/site/asdf/reports/site-health
"
exit 0
