#!/bin/zsh

# Usage
# v-stand

red=$(ts 196)
blue=$(ts 123)
grey=$(ts 245)

echo "
    $red prior to running setup.sh :
    $blue ~ sudo apt install build-essential libssl-dev libffi-dev python-dev
    $blue ~ sudo apt install libjpeg-dev zlib1g-dev
    $grey because the Cryptography library will not build using PIP

    $blue sudo apt install net-tools $grey installs ifconfig

"
exit 0

#    earlier fixes:
#    $c1 install additional libs for wxpython: $c2
#    ~ sudo apt-get install libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev 
#    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk 
#    libharfbuzz-dev libfribidi-dev libxcb1-dev
#
#    $c1 install snowflake-connector-python dependencies for specific python version;
#       see instructions at: $c2
#    https://docs.snowflake.com/en/user-guide/python-connector-install.html#openssl-and-ffi-linux-only
