#!/bin/zsh

# Description
# todo list 

# Usage
# todo 

c1="$(tput setaf 196)"
c2="$(tput setaf 241)"

echo "$c1
    ==============================================
$c2      architecture for a multi-region table of bldg. names  (done)
$c2      metrics, etc. on serverless ?                         (done) $c1
    ==============================================
"

exit 0
