#!/bin/zsh

# Description
# todo list 

# Usage
# todo 

c1="$(tput setaf 196)"
c2="$(tput setaf 241)"

echo "$c1
    ==============================================
$c2    1) is CRDB a fork of postgres ?  compatability ?  (done)
$c1    2) architecture for a multi-region table of bldg. names
$c2    3) metrics, etc. on serverless ?
    ==============================================
"

exit 0
