#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;
clear;

echo "$gr 
                VS repos & cd aliases $g

        ven       $k   ~/code/ventacity                    $g
        iaql      $k   ~/code/ventacity/iaq-lambda         $g
        vu        $k   ~/code/ventacity/vutility           $g
        ms        $k   ~/code/ventacity/milesight          $g
        abm       $k   ~/code/ventacity/milesight/ABM      $g
        dch       $k   ~/code/ventacity/devices            $g
        uih       $k   ~/code/ventacity/ui-helper          $g
        kr        $k   ~/code/cockroachdb                  $g
        pb        $k   ~/code/aws/push_button              $g
        sub       $k   ~/code/aws/subscriber               $g
        dest      $k   ~/code/aws/destinations             $g
        vul       $k   ~/code/aws/vu_lambda                $g
        za        $k   ~/code/shell/scripts/aws            $g

"
exit 0
