#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;
clear;

echo "$gr 
                VS repos & cd aliases $g

        ven       $k   ~/code/ventacity                          $g
        iaql      $k   ~/code/ventacity/iaq-lambda               $g

        vut       $k   ~/code/ventacity/vutility                 $g
        hdd       $k   ~/code/ventacity/vutility/hdd             $g
        vul       $k   ~/code/ventacity/vutility/vu_lambda       $g

        inva      $k   ~/code/aws/inventory                      $g
        pb        $k   ~/code/aws/push_button                    $g
        sub       $k   ~/code/aws/subscriber                     $g
        dest      $k   ~/code/aws/destinations                   $g

        ms        $k   ~/code/ventacity/milesight                $g
        abm       $k   ~/code/ventacity/milesight/ABM            $g
        dch       $k   ~/code/ventacity/devices                  $g
        uih       $k   ~/code/ventacity/ui-helper                $g
        kr        $k   ~/code/cockroachdb                        $g
        za        $k   ~/code/shell/scripts/aws                  $g
"
exit 0
