#!/bin/zsh

# Usage
# ven-wan

c1="$(tput setaf 87)"

c2="$(tput setaf 229)"
c3="$(tput setaf 250)"

echo "$c
\t Multitech Conduit model: MTCAP-915-001A Firmware 6.0
\t 192.168.0.55
\t u/n admin
\t p/w $CDT

\t deveui 44-91-60-00-00-f7-c2-73

"

exit 0
