#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;
clear;

echo "$pg
            Figure out how to make a Mac act like a DHCP server,
            so we can field connect to our gateways which are always
            going to be configured for DHCP.
$x
        DHCP stands for Dynamic Host Configuration Protocol, which is a network management protocol used
        to assign IP addresses and other network configuration parameters to devices on a network.
        A DHCP server is a computer program that provides this service to devices that request an
        IP address and other network settings.

        In other words, a DHCP server automatically assigns IP addresses to devices on a
        network, so that network administrators do not have to manually assign each IP address.
        DHCP also provides other important network configuration parameters, such as subnet mask, default
        gateway, and DNS server information.

        When a device connects to a network, it sends a broadcast message requesting an
        IP address from the DHCP server. The DHCP server responds with an available IP
        address and other network configuration parameters, which the device then uses to connect to
        the network.

        DHCP is commonly used in local area networks (LANs), such as home or
        office networks, to make it easier to manage and configure network settings for multiple
        devices.
     ................................................................................................
$s
    To set up your MacBook as a DHCP server, you can use the built-in macOS Internet Sharing feature,
    which allows you to share your Internet connection with other devices and configure your MacBook
    as a DHCP server. Here are the steps to set up your MacBook as a DHCP server:

$r    1. $k Connect your MacBook to the network that you want to provide DHCP service for.

$r    2. $k Go to System Preferences and click on Sharing.

$r    3. $k Select the Internet Sharing option from the left-hand pane.

$r    4. $k Choose the Internet connection that you want to share from the \"Share your connection from\"
        drop-down menu. This can be either Ethernet or Wi-Fi,
        depending on how you are connected to the network.

$r    5. $k Check the box next to \"Wi-Fi\" in the \"To computers using\" section to enable Wi-Fi sharing.

$r    6. $k Click on the \"Wi-Fi Options\" button to configure your Wi-Fi network.
        Set a network name, choose a security option and set a password.

$r    7. $k Click on the \"Internet Sharing\" checkbox to enable Internet Sharing and start the DHCP service.


    Your MacBook should now be acting as a DHCP server and providing IP addresses
    and network settings to devices on the network that connect to the Wi-Fi network
    you just created.

$h       System Settings > General > Sharing > Internet Sharing
     ................................................................................................
$x
            To connect your MacBook to a MultiTech gateway
            using the Mac's DHCP server, follow these steps:

        1  Connect your MacBook to the MultiTech gateway using an Ethernet cable.
        2  Go to the Apple menu on your MacBook and select System Preferences.
        3  Click on Network and select Ethernet from the list on the left.
        4  Click on the Advanced button in the bottom right corner.
        5  Go to the TCP/IP tab and select Using DHCP from the Configure IPv4 drop-down menu.
        6  Click OK to save the changes.
        7  Open Terminal on your MacBook by going to the Applications folder and selecting Utilities.
        8  In the Terminal window, run 
    $h
            sudo launchctl load -w /System/Library/LaunchDaemons/bootps.plist
    $x
            and press Enter. This will start the DHCP server on your Mac.
        9  Once the DHCP server is running, your MacBook will assign an IP address to the MultiTech gateway automatically.
       10  You should now be able to access the MultiTech gateway from your MacBook using the assigned IP address.
            Note: Make sure that the Ethernet cable is securely connected to both the MacBook and the MultiTech gateway.

"

exit 0
