#!/bin/zsh

echo "                              $aqua
\t ===============================  $gold

\t      kW = V * A / 1000 

\t     kWh =  V * Ah / 1000         $aqua

\t ===============================
"

exit 0
