#! python3

from colored import fg

yellowish = fg(184)
pink = fg(183)
palegreen = fg(86)
blue = fg(45)
grey = fg(253)

s1 = grey + '''
    /Users/james/code/ventacity/sbg-webapp/modules/webapp-vue-ui/src/components/common/graphs 
     ('development' branch) 
 
      https://github.com/ventacity/sbg-webapp/pull/74 
 
    Patch Links: 
    https://github.com/ventacity/sbg-webapp/pull/74.patch 
    https://github.com/ventacity/sbg-webapp/pull/74.diff 
-------------------------------------------------------------------------------------------
'''
 
s2 = yellowish + '''
    For now, you can branch off of the latest develop. 
    From there I’d put a new component in modules/vue-ui/src/reports 
     (alongside the other report you created)

    I may need to help you link to the report since that involves delving into the old Vue app.
    Let me know when you get to that point!

    new route in: modules/vue-ui/src/router/index.ts
      {
        path: "/building/:buildingId/reports/energy",
        name: "buildingEnergyReport",
        component: BuildingEnergyReport
      },

    The other report is at …/reports/iaq, so it seems like …/reports/energy makes sense.
'''

s3 = palegreen + '''
\t The tests compare the DOM-generated layout to ensure no unsuspecting changes have been made.
\t For the most part, these are innocuous, but it is best to always review snapshot failures to make 
\t sure things didn’t get accidentally broken. They go out of date whenever we update or make changes 
\t to the snapshotted components, however. To update the snapshots that are out of date,
\t you can run the following or an analogous command: (cd modules/vue-ui && npx jest --updateSnapshot) .
'''

s4 = yellowish + '''
\t Start on the latest develop (make sure you pull to get latest)
\t Create a new branch: git switch -c new-branch-name-here
\t Grab those commits from your other branch: git cherry-pick 3e12be011 687c0741d
\t Push the new branch to Github: git push -u origin
'''

print(s1, s2, s3, s4)
