#! python3

from colored import fg

yellowish = fg(184)
pink = fg(183)
palegreen = fg(86)
blue = fg(45)
grey = fg(253)

s1 = grey + '''
    /Users/james/code/ventacity/sbg-webapp/modules/webapp-vue-ui/src/components/common/graphs 
     ('development' branch) 
 
      https://github.com/ventacity/sbg-webapp/pull/74 
 
    Patch Links: 
    https://github.com/ventacity/sbg-webapp/pull/74.patch 
    https://github.com/ventacity/sbg-webapp/pull/74.diff 
-------------------------------------------------------------------------------------------
'''
 
s2 = yellowish + '''
    For now, you can branch off of the latest develop. 
    From there I’d put a new component in modules/vue-ui/src/reports 
     (alongside the other report you created)

    I may need to help you link to the report since that involves delving into the old Vue app.
    Let me know when you get to that point!

    new route in: modules/vue-ui/src/router/index.ts
      {
        path: "/building/:buildingId/reports/energy",
        name: "buildingEnergyReport",
        component: BuildingEnergyReport
      },

    The other report is at …/reports/iaq, so it seems like …/reports/energy makes sense.
'''
print(s1, s2)
