#!/bin/zsh

echo "$gold
{
    'tmst': 2926733555,
    'chan': 3,
    'rfch': 0,
    'freq': 902.9,
    'stat': 1,
    'modu': 'LORA',
    'datr': 'SF7BW125',
    'codr': '4/5',
    'lsnr': 9.5,
    'rssi': -43,
    'opts': '',
    'size': 3,
    'fcnt': 18,
    'cls': 0,
    'port': 2,
    'mhdr': '4010779d00801200',
    'data': 'Ew4A',
    'appeui': 'ea-9c-9d-e6-4f-0f-c9-26',
    'deveui': '44-91-60-00-00-f7-c2-73',
    'name': 'JamesDevA',
    'devaddr': '009d7710',
    'ack': False,
    'adr': True,
    'gweui': '00-80-00-00-00-01-f8-e1',
    'seqn': 18,
    'time': '2022-11-03T19:50:10.144137Z'
}
"

exit 0
