#!/bin/zsh

# milesight order

echo "$pink
    Milesight IoT Sensors: $green
        AM107 (DONE)
        AM104
        AM103
        EM320 (DONE)
        EM300
        EM500
        VS121
        VS132
"
exit 0
