#!/bin/zsh

# Author: James Batman
# Date Created: 
# Last Modified: 

# Description
# 

# Usage
# 
echo "$red

\t  what would you like to monitor with a sensor?
\t  https://js.masterpassword.app

\t  


"

exit 0
