#!/bin/zsh

# Description
# occupancy sensors 

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;
clear;

echo "$pink VS121 $grey
   default IP of sensor         192.168.1.1          
   default SSID                 Workplace Sensor_XXXXXX
   password                     UzzULs67hQaiGEg

$pink VS132 $grey
   default IP of Ethernet port is 192.168.5.220
   default IP of Wi-Fi is 192.168.1.1
   default SSID is People Counter_XXXXXX

$x =========================================================================================== 

$aqua
   VS121-915M notes  $grey
    covers ~ 800 sq. ft.
    ceiling or wall mountable
    according to MS, counts moving objects if human as high as 98% accuracy 
    map up to 16 custom regions - count in each region
    count people crossing a line, in / out 

    $red use cases $grey
    - find vacant, available meeting rooms, & optionally schedule an available room

    - add MS D2D (device-to-device) to connect other devices for intelligently responding to person count,
        e.g. turn on or off lights or heat (energy saving)

$x =========================================================================================== 

$aqua
   VS132-915M notes $grey
    - restart browser and/or clear cache if GUI is malfunctioning
    - reporting period is very regular -- set in GUI
    - when configuring the Pass Area ROI (region of interest) in the GUI,
        draw the Entrance Area at the top of the field
        and the Exit Area at the bottom of the field

     data: $p
       \"people_in\": 1,                       
       \"people_out\": 1,                      
       \"total_counter_in\": 2,                
       \"total_counter_out\": 2

$x =========================================================================================== 
 $k
    Start with looking at the form of the data from $a
     AM308 (motion / PIR)
     VS121
     VS132 $k
    And try to define an MVP that would be cool and work with as many of those as possible

"

exit 0
