#!/bin/zsh

# current project notes
r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

echo "$h
    web hooks
    ABM
    Lambda
    Milesight TVOC 1-5 (or ppb)
"

exit 0
