#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

echo "$s
query Building {
  building(buildingUuid: \"4e4648b4-dd2e-47d6-896d-3ca86ce1dabe\") {
    assets(knownAssets: true) {
      assetUuid
      knownAssetUuid
      name
      floor {
        position
        name
      }
      assetHealth(startDate: \"2023-06-25T00:00:00\", endDate: \"2023-06-25T23:59:59\") {
        normalTimePct
        propertyName
      }
    }
  }
}
"

exit 0

query MyQuery {
  siteHealthOverTime(startDate: \"2022-04-01T00:00:00\",
                     endDate: \"2022-04-30T00:00:00\",
                     siteUuid: \"5974610d-ee02-477b-bc6b-059b8a2aa081\") {
    sensors {
      normalTimePct
      sensor
    }
    zone {
      id
      name
      floor {
        id
        level
        name
      }
    }
  }
}

query l {
  latestEnergy(deviceUuid: \"7b794dd5-e29c-4851-a533-100c57dc4cff\") {
      time
      minA
      maxA
      avgA
      kW
  }
}

query Energy {
  energyConsumptionByTime(
    deviceUuid: \"7b794dd5-e29c-4851-a533-100c57dc4cff\",
    startDate: \"2022-07-19\",
    endDate: \"2022-08-18\") {
    points {
      time
      kWh
    }
  }
}

query lineGraph {
  metricSeriesEnergy(deviceUuid: \"7b794dd5-e29c-4851-a533-100c57dc4cff\", 
    filter: {
      metric: AVERAGE,
      startDate: \"2022-07-19\", 
      endDate: \"2022-07-30\", 
      sensor: MA,
      granularity: 10})
}
