#!/bin/zsh

echo "$sea
query MyQuery {
  siteHealthOverTime(startDate: \"2022-04-01T00:00:00\",
                     endDate: \"2022-04-30T00:00:00\",
                     siteUuid: \"5974610d-ee02-477b-bc6b-059b8a2aa081\") {
    sensors {
      normalTimePct
      sensor
    }
    zone {
      id
      name
      floor {
        id
        level
        name
      }
    }
  }
}

query l {
  latestEnergy(deviceUuid: \"7b794dd5-e29c-4851-a533-100c57dc4cff\") {
      time
      minA
      maxA
      avgA
      kW
  }
}

query Energy {
  energyConsumptionByTime(
    deviceUuid: \"7b794dd5-e29c-4851-a533-100c57dc4cff\",
    startDate: \"2022-07-19\",
    endDate: \"2022-08-18\") {
    points {
      time
      kWh
    }
  }
}

query lineGraph {
  metricSeriesEnergy(deviceUuid: \"7b794dd5-e29c-4851-a533-100c57dc4cff\", 
    filter: {
      metric: AVERAGE,
      startDate: \"2022-07-19\", 
      endDate: \"2022-07-30\", 
      sensor: MA,
      granularity: 10})
}

"

exit 0
