#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$gr

    vue serve  $k <ComponentName.vue>       $x serve a single .vue file as a full project with no project setup
                                           use case: quick prototyping of a single component $gr
    vue build  $k <ComponentName.vue>       $x build a single .vue file into a minified, production-ready JS file
                                           use case: compile a single .vue file for use in another project $gr
    vue add    $k <@vue/cli-plugin-babel>   $x installs a plugin and invokes its generator
                                           use case: add a new capability to project (e.g. TS or PWA) $gr

    vue invoke $k <vuetify>                 $x invoke the generator of a plugin in an already created project
                                           use case: you've manually added a plugin and want to run its setup script $gr
    vue upgrade $k                          $x upgrade pkgs and run migrations: 
                                           upgrade to a newer version of Vue CLI or any installed plugins $gr

    npm update vue $k                       $x update Vue.js in an existing project $gr
    npm show vue version $k                 $x show the latest version of Vue.js $gr
    npm install -g @vue/cli $k              $x install latest version of vue globally $gr

    vue add vuetify $k                      $x adds the vuetify cli plugin to the project $gr
    vue create $k <project-name>            $p << start project $gr
"

exit 0
