#!/bin/zsh

# Description
# delete the contents of a file 

# Usage
# 0 <file_name>

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

echo "$g
  Are you sure you want to empty the contents of the file,$c $1$g? [y/N] $p"
read answer

if [[ $answer = [yY] || $answer = [yY][eE][sS] ]]
then
    truncate -s 0 "$1"
    echo "$g  The file, $c$1$g, has been emptied."
else
    echo "$g  No changes were made to the file,$c $1$g."
fi

exit 0
