#! python
import os
import sys
import argparse
import psycopg2


cr_user     = os.getenv('CR_USER')
cr_pw       = os.getenv('CR_PW')
cr_host     = os.getenv('CR_HOST')
cr_port     = os.getenv('CR_PORT')
cr_database = os.getenv('CR_DATABASE')

deveuis = sys.argv[1: ]
deveuis = [s.lower() for s in deveuis]


def query_crdb(deveuis=[]):

    try:
        conn = psycopg2.connect(
            user=cr_user,
            password=cr_pw,
            host=cr_host,
            port=cr_port,
            database=cr_database
        )
        query = f'''
            SELECT serial_number AS deveui, registry_uuid
            FROM ubx_device_registry
            WHERE serial_number IN %s
        '''
        cur = conn.cursor()
        cur.execute(query, (tuple(deveuis),))
        return cur.fetchall()

    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: ", error)

    finally:
        if conn is not None:
            cur.close()
            conn.close()


rows = query_crdb(deveuis=deveuis)
print('deveui'.rjust(25), 'registry_uuid'.rjust(40))
for r in rows:
    print(r[0].rjust(25), r[1].rjust(40))
