#!python3
'''
    building_uuid -> dev_eui, model_name 
    Provide building_uuid to get a CSV with headers []
'''
import os
import csv
import pandas as pd
import argparse
from colored import fg
import subprocess as sp
from db import cursor_iterator


outfile = 'output.csv'


def parse_arguments(): #TODO
    parser = argparse.ArgumentParser(description='produces output.csv with headers \
            []')
    parser.add_argument('building_uuid', type=str, help='provide a building_uuid')
    return parser.parse_args()


building_uuid = parse_arguments().building_uuid
params        = (building_uuid,)

query = '''
    SELECT d.dev_eui, k.model_name
    FROM ubx_asset a
    JOIN ubx_device d
    ON a.asset_uuid = d.asset_uuid
    JOIN ubx_known_asset k
    ON a.known_asset_uuid = k.known_asset_uuid 
    WHERE a.building_uuid = %s
    ORDER BY k.model_name;
'''

with open(outfile, 'w', newline='') as f:
    writer = csv.writer(f)

    with cursor_iterator(query, params, 'prod') as cur:
        headers = [desc[0] for desc in cur.description]
        writer.writerow(headers)
        for row in cur:
            writer.writerow(row)


sp.run(['clear'])
sp.run(['bat', outfile])
