#!python3
'''
    provide model_name
'''
import os
import csv
import pandas as pd
import argparse
from colored import fg
import subprocess as sp
from db import cursor_iterator


outfile = 'output.csv'


def parse_arguments():
    parser = argparse.ArgumentParser(description='produces output.csv with headers \
            []')
    parser.add_argument('model_name', type=str, help='provide a ka_uuid')
    return parser.parse_args()


model_name  = parse_arguments().model_name.upper()
params      = (f"%{model_name}%",)

query = '''
    SELECT
        model_name,
        known_asset_uuid,
        properties -> 'valid_properties' AS valid_properties 
    FROM ubx_known_asset 
    WHERE model_name LIKE %s
'''

with open(outfile, 'w', newline='') as f:
    writer = csv.writer(f)

    with cursor_iterator(query, params, 'prod') as cur:
        headers = [desc[0] for desc in cur.description]
        writer.writerow(headers)
        for row in cur:
            writer.writerow(row)


sp.run(['clear'])
sp.run(['bat', outfile])
