#!/bin/zsh

grey=$(ts 252)
lightblue=$(ts 153)
gold=$(ts 220)
pale=$(ts 242)
salmon=$(ts 216)

echo "
$salmon ---------------------------------------------------------------------------------------------------------------

$grey 
\t # UUID's created via PSQL's gen_random_uuid() $lightblue

\t site_uuid     = '9f02171a-32a0-4695-a7f2-aad43528af58'
\t device_A_uuid = 'a2204077-054e-49f3-ba0c-17a34cd01800'  $grey# Phase-A-DA9D $lightblue
\t device_B_uuid = '7b794dd5-e29c-4851-a533-100c57dc4cff'  $grey# Phase-B-0673 $lightblue
\t device_C_uuid = 'ef66fc2c-3c42-458c-abc7-cbfe9aca52ac'  $grey# Phase-C-8DFB $lightblue

$salmon ---------------------------------------------------------------------------------------------------------------

\t SQL
$grey 
\t table columns: $lightblue 
\t SITEUUID, DEVICEUUID, STAMP, DEVICE_TYPE, DEVICE_ID, DATA, DATECREATED, SERVER_SOURCE

$grey 
\t query: $lightblue
\t select date(STAMP), count(*), SITEUUID, DEVICEUUID, DEVICE_TYPE from \"SBG\".\"SBG_STATE_TRANSFER\"
\t where DEVICE_TYPE = 'VU-HOTDROP' and SITEUUID = '9f02171a-32a0-4695-a7f2-aad43528af58'
\t group by date(STAMP), DEVICEUUID, DEVICE_TYPE, SITEUUID
\t order by DEVICEUUID, date(STAMP);
"

exit 0
