#!/bin/zsh

d=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

echo "
$g        upl            $x update Lambda      $h   upl <lambda-function-name>    
$g        get-layer      $x get Layer          $h   get-layer <name-of-layer>     
$g        pub-layer      $x publish Layer      $h   pub-layer <name-of-layer>     
"

exit 0
