#!python3

# Usage

import json
import sys
import boto3
from botocore.exceptions import NoCredentialsError
from colored import fg


light_goldenrod = fg(186)


def get_secret():
    region_name = 'us-west-2'
    secret_name = 'JamesCRDB'
    secret_key  = 'DSN'

    session = boto3.session.Session()
    client = session.client(service_name='secretsmanager', region_name=region_name)

    try:
        get_secret_value_response = client.get_secret_value(SecretId=secret_name)
    except NoCredentialsError:
        print('No credentials to access Secrets Manager.')
        return None

    if 'SecretString' in get_secret_value_response:
        secret = get_secret_value_response['SecretString']
    else:
        print('Secret is binary. This example handles only text secrets.')
        return None

    secret_dict = json.loads(secret)
    dsn_value = secret_dict.get(secret_key, 'DSN key not found in secret.')

    return dsn_value

if __name__ == '__main__':
    secret_value = get_secret()
    if secret_value:
        print('The value of the DSN key is: \n', light_goldenrod, f'{ secret_value }\n')


