#!python3

# Description
# package & update Lambda functions 

# Usage
# pu <py-file> <name-of-lam-fcn>

import os
import sys
import boto3
import zipfile
from colored import fg


py_file  = sys.argv[1]
fcn_name = sys.argv[2]

pkg = 'package.zip'

def update_lambda_function(py_file, function_name):

    with zipfile.ZipFile(pkg, 'w') as zf:
        zf.write(py_file)

    lambda_client = boto3.client('lambda')

    with open(pkg, 'rb') as f:
        zipped = f.read()

    response = lambda_client.update_function_code(
        FunctionName=function_name,
        ZipFile=zipped,
    )

    os.remove(pkg)
    return response
