#!python3

# Description:  package & update Lambda functions 
# Usage         publam <name-of-lam-fcn>
import os
import sys
import boto3
import zipfile


f_name = sys.argv[1]
py_file  = 'lambda_function.py'
crt_file = 'root.crt'
pkg      = 'package.zip'


def update():
    client = boto3.client('lambda')
    with zipfile.ZipFile(pkg, 'w') as f:
        f.write(py_file)
        f.write(crt_file)

    with open(pkg, 'rb') as f:
        zipped = f.read()

    response = client.update_function_code(
        FunctionName=f_name,
        ZipFile=zipped,)
        #Publish=True) # automatically create a new version 

    os.remove(pkg)
    print(response['FunctionArn'])


update()
