#! python
# Description
# convert base64 to hex 

import sys
import binascii
from colored import fg


xs = sys.argv[1:]

col1 = fg(150)
col2 = fg(154)
col3 = fg(213)


def base64_to_hex(n):
    b = binascii.a2b_base64(n)
    return binascii.hexlify(b).decode('utf-8')


def pretty_print(xs, ys):
    print()
    #print(col3 + 'base64'.rjust(42) + '\n' + col3 + 'hex'.rjust(72))
    for idx in range(len(xs)):
        x, y = xs[idx], ys[idx]
        print(col3 + 'base64: '.rjust(10) + '\n ' + col1 + x)
        print(col3 + 'hex: '.rjust(10) + '\n ' + col2 + y)
    print()


ys = [base64_to_hex(x) for x in xs]
pretty_print(xs, ys)
