#! python3
import sys
from colored import fg
from sys import argv

'''
convert cm to inches 
1 cm = 0.393701 inches
'''

color = fg(214)

def cm_to_in(cm):
    return round(cm * 0.393701, 2)
 
def print_usage():
    print(' usage: cm-in <number> <number>..')

def print_numbers(ns):
    print()
    [print(color + str(n).rjust(10), end='') for n in ns]
    print('\n')


try:
    xs = [int(s) for s in argv[1 : ]]
    ys = [cm_to_in(x) for x in xs] 
    print_numbers(ys)
except:
    print_usage()
