#! python

# Description
# convert EUR to SRD 
from sys import argv
from colored import fg


eur_per_usd = 0.92

eur = float(argv[1])
usd = eur * (1 / eur_per_usd)
usd = round(usd, 2)
print()
print(fg(190) + '\t' +  str(usd))
print()



