#! python
# Description
# convert hex to base64

import sys
import binascii
from colored import fg


xs = sys.argv[1:]

c1 = fg(150)
c2 = fg(154)
c3 = fg(213)


def hex_to_base64(n):
    b = binascii.unhexlify(n)
    return binascii.b2a_base64(b, newline=False).decode('utf-8')


def pretty_print(xs, ys):
    print()
    for idx in range(len(xs)):
        x, y = xs[idx], ys[idx]
        print(c3 + ' hex: ' + c1 + x)
        print(c3 + ' b64: ' + c2 + y)
    print()


ys = [hex_to_base64(x) for x in xs]
pretty_print(xs, ys)
