#! python
# Description
# convert hex to base64

import sys
import binascii
from colored import fg


xs = sys.argv[1:]

c1 = fg(150)
c2 = fg(154)
c3 = fg(213)


def hex_to_base64(n):
    b = binascii.unhexlify(n)
    return binascii.b2a_base64(b).decode('utf-8').strip()


def pretty_print(xs, ys):
    print()
    print('\t' + c3 + 'hex'.rjust(24) + c3 + 'base64'.rjust(48))
    for idx in range(len(xs)):
        x, y = xs[idx], ys[idx]
        print('\t' + c1 + x.rjust(24) + c2 + y.rjust(48))
    print()


ys = [hex_to_base64(x) for x in xs]
pretty_print(xs, ys)
