#! python
# Description
descr = '''convert hex strings to ints'''
import sys
import binascii
import argparse
from colored import fg


c1, c2, c3 = fg(150), fg(154), fg(213)


def parse_arguments():
    parser = argparse.ArgumentParser(description=descr)
    parser.add_argument('-l', '--little', action='store_true', help='optional flag - if present, use little endian byte order')
    parser.add_argument('-s', '--signed', action='store_true', help='optional flag - if present, signed ints')
    parser.add_argument('hex_strings', type=str, nargs='*', help='hex strings to be processed')
    return parser.parse_args()


args        = parse_arguments()
hexes       = args.hex_strings
byteorder   = 'little' if args.little else 'big'
signed      = args.signed


def hex_to_int(h):
    bytes_value = bytes.fromhex(h)
    return int.from_bytes(bytes_value, byteorder=byteorder, signed=signed)


def pretty_print(xs, ys):
    col1, col2 = 18, 12
    print()
    print(c3 + 'hex'.rjust(col1) + c3 + 'int'.rjust(col1))
    for idx in range(len(xs)):
        x, y = xs[idx], ys[idx]
        print(c1 + x.rjust(col1) + c2 + y.rjust(col1))
    print()


ints = [str(hex_to_int(h)) for h in hexes]
pretty_print(hexes, ints)
