#! python
# Description
# convert hex to int 


import sys
import binascii
from colored import fg


xs = sys.argv[1:]

c1 = fg(150)
c2 = fg(154)
c3 = fg(213)


def hex_to_int(n):
    return str(int(n, 16))


def pretty_print(xs, ys):
    print()
    print('\t' + c3 + 'hex'.rjust(24) + c3 + 'int'.rjust(48))
    for idx in range(len(xs)):
        x, y = xs[idx], ys[idx]
        print('\t' + c1 + x.rjust(24) + c2 + y.rjust(48))
    print()


ys = [hex_to_int(x) for x in xs]
pretty_print(xs, ys)
