#! python

# Description
# 

# Usage
# 
import sys
from sys import argv
from colored import fg


h = argv[1]
bytes_value = bytes.fromhex(h)
decimal_value = int.from_bytes(bytes_value, byteorder='little', signed=True)
print(fg(190), decimal_value)
