#! python
'''
 Convert hexstrings in little endian byteorder to ints, i.e. h-i --little == "hil"
 (convenience script)
'''
from sys import argv
from colored import fg


c1, c2, c3 = fg(150), fg(154), fg(213)


def hex_to_int(h):
    bytes_value = bytes.fromhex(h)
    return int.from_bytes(bytes_value, byteorder='little', signed=False)


def pretty_print(xs, ys):
    col1, col2 = 18, 12
    print()
    print(c3 + 'hex'.rjust(col1) + c3 + 'int'.rjust(col1))
    for idx in range(len(xs)):
        x, y = xs[idx], ys[idx]
        print(c1 + x.rjust(col1) + c2 + y.rjust(col1))
    print()


hexes = argv[1:]
ints = [str(hex_to_int(h)) for h in hexes]
pretty_print(hexes, ints)
