#! python
# Description - convert integers to hex 


import sys
import binascii
from colored import fg


xs = sys.argv[1:]

c1 = fg(150)
c2 = fg(154)
c3 = fg(213)


def int_to_bytes(n, byteorder='big'):
    return n.to_bytes((n.bit_length() + 7) // 8, byteorder)


def int_to_hex(n):
    b = int_to_bytes(n)
    return binascii.hexlify(b).decode('utf-8')


def pretty_print(xs, ys):
    print()
    print('\t' + c3 + 'int'.rjust(24) + c3 + 'hex'.rjust(48))
    for idx in range(len(xs)):
        x, y = xs[idx], ys[idx]
        print('\t' + c1 + x.rjust(24) + c2 + y.rjust(48))
    print()


ys = [int_to_hex(int(x)) for x in xs]
pretty_print(xs, ys)
