#! python

# Description
# convert SRD to USD
from sys import argv
from colored import fg


srd_per_usd = 36.8

srd = float(argv[1])
usd = srd * (1 / srd_per_usd)
usd = round(usd, 2)
print()
print(fg(190) + '\t' +  str(usd))
print()
