#!/bin/zsh

# Description
# Convert F to C or C to F

# Usage
# temp -[f | c] 30

if [ -z $1 ] || [ -z $2 ]; then
    echo " usage: temp -f 65 (convert 65 F to C)"
fi

while getopts "f:c:" opt; do
    case $opt in
        c) echo "scale=2; ($OPTARG * 9 / 5) + 32" | bc;;
        f) echo "scale=2; ($OPTARG - 32) * 5 / 9" | bc;;
        \?) ;;
    esac
done


exit 0
