#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew;

clear;

echo "$k
\t Learn anything & everything you're interested in.
\t  resoures: $s
\t    Udemy, Coursera, YouTube, books, chatGPT $r

\t  Python
\t  Bash / Zsh CLI + shell scripting
\t  Git & Github
\t  text editor: VSCode as a tool + 1 other: Vim or Emacs (opt)

\t  SQL
\t  HTML, CSS, JS, & a JS framework
"


exit 0
