#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$gr 
    Longevity molecules $p
    rapamycin
    aspirin
    acarbose
    $gr 
    also rans $p
    resv, fish oil, curcumin, MCT oil, oxaloacetic acid, metformin
    methylene blue, MitoQ, NR, fisetin, ashwagandha 
"

exit 0
