#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$gr
            ==============================
            PDX -> Phoenix, Southwest 4108
            Monday, May 20, dep. 7:15 AM
            ==============================
$rs
            ==============================
            Phoenix -> PDX, Southwest 2525
            Tuesday, May 28, arr. 5:35 PM
            ==============================

"
exit 0
