#! python
import sys
from colored import fg


p_and_i = 1134
starlink = 60
fzdxx_interest_rate = 0.0515
downpayment = 50000
interest = round(fzdxx_interest_rate * downpayment / 12)

monthly = p_and_i + starlink + interest
monthly = round(monthly)
print('\n',
      fg(246), 'mtg + Starlink + (5.15% * 50_000)/12 \n',
      fg(201), f'{p_and_i} + {starlink} + {interest}',
      fg(246), '=' ,
      fg(193), f'{monthly}', '\n')
