#!/bin/zsh

r=$red; g=$gold; y=$yellow; a=$aqua; pg=$palegreen; k=$khaki;
c=$cyan; x=$grey; s=$sea; gr=$green; p=$pink; h=$honeydew; rs=$rose;
z="$(tput setaf 229)"
clear;

echo "$rs
    Graminex $k             - pollen extract $rs
    Fisetin $k              - apples, kiwi, kale, strawberries (kills candida) $rs
    Luteolin $k             - $rs
    Monolaurin $k           - (kills candida) coconut $rs
    Oregano $k              - (completely inhibit growth candida)  $rs
    Grapeseed extract $k    - (kills candida)  $rs
    Muira Puama $k          - (kills candida)  $rs
    Lycopene
 $x
  ===========================================================================================
$g
    aromatase$h activity increases with age, catalyzes testosterone -> estrogen, causes BPH $g
    --------- $h
    these raise aromatase activity (not good): $r 
      body fat, insulin, high-carb diet, alcohol, whole grains. $h

    these lower aromatase activity (good): $gr  
      cruciferous vegetables, flaxseed, green tea, citrus peel
"

exit 0
